### PR TITLE
Add appstream metadata improvement patch

### PR DESCRIPTION
**Pull request by Mazhoon**
Adding the changes from upstream that should fix the split by filling in the provides and replaces tags.

(Didn't actually test the commit in this PR in any way yet.)

### CODE REVIEW

**Review by travier — APPROVED** [review]

**Comment by travier** [comment]
bot, build

**Comment by travier** [comment]
@Mazhoon Can you test this build? Thanks

**Comment by Mazhoon** [comment]
> @Mazhoon Can you test this build? Thanks

Sure. Tried installing on a fresh system with `flatpak install --user https://dl.flathub.org/build-repo/104245/org.kde.amarok.flatpakref` - installation worked, program started, I managed to scan some audio files and play one of them, so I guess everything's ok? Or is there something specific I should still check out?

**Comment by travier** [comment]
If it's correctly reported as installed in Discover/Software for the right name maybe?

**Comment by Mazhoon** [comment]
Hmm, a bit strange behaviour on Discover 6.0.4. Amarok Flatpak is listed as installed. On first Discover start after installation, everything seemed pretty normal, but starting Discover again, it shows a notification "Amarok is not installed but it still has data present" and offers a button to delete settings and user data. However, remove and launch button are there and function correctly. If I remove the manually installed Flatpak, an "Install from 'user'" button is available afterwards, but it does not function.

When searching for Amarok, I also get the distribution-provided package listed as separate entry with "Install from openSUSE Tumbleweed" button there. Clicking the Flatpak Amarok in list shows its details, but the openSUSE one remains selected in the list.

I also tried adding flathub-beta. If I search with Home category active, I get one result from the distribution package repository and one from Flathub beta. However, after activating any of the other categories, the Flathub beta one gets replaced by the manually installed in all results (I can see it again only after restarting Discover). I think Discover gets pretty confused by the manually installed flatpak.

As background, I must note that I've never used any other Flatpaks on that device, and Amarok is installed from sources there. Not sure if that causes some of the strangeness. 
However, the fact that the distribution one has sharing URL "appstream://org.kde.amarok.desktop" and the separate Flatpak one "appstream:org.kde.amarok" suggests that there's at least something Discover doesn't handle quite correctly, but I'd figure that would be something to fix in Discover if it works correctly in some other software managers.

**Comment by Mazhoon** [comment]
Included in 3.0.1

**Pull request closed without merging**
